### PR TITLE
Four quick changes

### PR DESCRIPTION
**Pull request by gpellis**
This PR contains four commits that are as independent as possible. The first two are doc updates and library version bump. The third is the only one that affects the actual operation of the template and fixes a bug. The fourth fixes some symlinks so they work when the repo is cloned. Feel free to just cherrypick.

### CODE REVIEW

**Comment by awkay** [comment]
So, part of what I do on a new version of the template is generate an app with an unusual name, and make sure the main build, cards, and tests all work. Did you do this? In particular, a name with a hypen (and it sounds like perhaps a dot).

**Comment by gpellis** [comment]
You are correct, I forgot to check it with a hyphen and that is indeed broken in this case. It will require a slightly bigger change to make it work. Will do that now. Do you like the other changes? I can split stuff out into multiple PRs if that is better.

**Comment by awkay** [comment]
It all looks good. Nice to have someone else working on it to find silly things like symlinks that point to absolute paths on my machine :)

**Comment by awkay** [comment]
Did you finish testing?

**Comment by gpellis** [comment]
It seemed to work with the testing I did. Though it was just trying random things, so there may still be something I missed. `lein new fulcro domain.proj-name nodemo shadow-cljs` is what I focused on and everything I know to play with seems to work in that case. If there is a more specific set of test you'd like me to run, I'd be happy to.

**Comment by awkay** [comment]
Just that the tests, cards, main, and server all work. If that passes, then we're good.

**Comment by gpellis** [comment]
Then we should be good. :-)

**Pull request merged**
